"""Reproducible diagnostics for properties the contract discloses.

A number quoted in the frozen record has to be re-derivable, at the scale it
claims to describe. The replenishment-churn asymmetry was first disclosed as a
one-off measurement taken at reduced scale, and it did not hold at the frozen
scale the confirmatory run uses. This module exists so that any figure in the
record can be regenerated by running a named function with named arguments.

Everything here runs on sentinel seeds. `run_once` refuses frozen seeds, so a
diagnostic cannot become a route to an outcome.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

from .mechanisms import FIFO, PRO_RATA
from .sim import run_once


# Fixed sentinel seeds, so the figures in the record are reproducible verbatim.
DIAGNOSTIC_SEEDS = tuple(range(900_000_001, 900_000_009))


@dataclass
class ChurnResult:
    seeds: tuple[int, ...]
    warm_up_events: int
    horizon_events: int
    latency_ms: int
    fifo_placements: tuple[int, ...]
    pro_rata_placements: tuple[int, ...]

    @property
    def fifo_mean(self) -> float:
        return sum(self.fifo_placements) / len(self.fifo_placements)

    @property
    def pro_rata_mean(self) -> float:
        return sum(self.pro_rata_placements) / len(self.pro_rata_placements)

    @property
    def excess_fraction(self) -> float:
        """How much more often pro-rata replaces its order than FIFO."""
        return (self.pro_rata_mean - self.fifo_mean) / self.fifo_mean

    @property
    def seeds_with_pro_rata_higher(self) -> int:
        return sum(1 for a, b in zip(self.fifo_placements, self.pro_rata_placements) if b > a)

    def summary(self) -> str:
        return (
            f"{len(self.seeds)} sentinel seeds at {self.warm_up_events} + {self.horizon_events} events, "
            f"latency {self.latency_ms} ms: FIFO {self.fifo_mean:.1f} placements, "
            f"PRO_RATA {self.pro_rata_mean:.1f}, excess {100 * self.excess_fraction:.1f}%, "
            f"pro-rata higher in {self.seeds_with_pro_rata_higher}/{len(self.seeds)} seeds"
        )


def measure_replenishment_churn(
    cfg,
    seeds: tuple[int, ...] = DIAGNOSTIC_SEEDS,
    warm_up_events: int | None = None,
    horizon_events: int | None = None,
    latency_ms: int | None = None,
) -> ChurnResult:
    """Count tracked-order placements per arm.

    A placement is one cancel-and-replace episode of the tracked display order.
    Defaults to the frozen scale, because that is the scale any disclosed figure
    has to describe.
    """
    run_cfg = cfg
    if warm_up_events is not None or horizon_events is not None:
        run_cfg = replace(
            cfg,
            warm_up_events=warm_up_events if warm_up_events is not None else cfg.warm_up_events,
            horizon_events=horizon_events if horizon_events is not None else cfg.horizon_events,
        )
    latency = cfg.matched_baseline_ms if latency_ms is None else latency_ms

    fifo, pro_rata = [], []
    for seed in seeds:
        fifo.append(run_once(run_cfg, FIFO, seed, latency).placements)
        pro_rata.append(run_once(run_cfg, PRO_RATA, seed, latency).placements)

    return ChurnResult(
        seeds=tuple(seeds),
        warm_up_events=run_cfg.warm_up_events,
        horizon_events=run_cfg.horizon_events,
        latency_ms=latency,
        fifo_placements=tuple(fifo),
        pro_rata_placements=tuple(pro_rata),
    )
